gfx/env/de_desertbk.tga
gfx/env/de_desertdn.tga
gfx/env/de_desertft.tga
gfx/env/de_desertlf.tga
gfx/env/de_desertrt.tga
gfx/env/de_desertup.tga
maps/de_desert.res
maps/de_desert.txt
models/de_desert/bush1.mdl
models/de_desert/bush2.mdl
models/de_desert/car.mdl
models/de_desert/grass.mdl
models/de_desert/shade.mdl
models/de_desert/tree.mdl
overviews/de_desert.bmp
overviews/de_desert.txt
sound/de_desert/station.wav
sound/de_desert/wind.wav